### ISSUE TITLE
Coworking companies in our space

### ISSUE THREAD

**Issue by yangwao** [Progressbar/progressbar-coweb#27]
Would be nice to have list of companies who are working on their product to show them little boost and could attract other coworkers as well

**Comment by olso** [comment]
Biotron, decent, minitech, treeti, dennik n, bielanoc?

What else?

**Comment by yangwao** [comment]
Payout, blockunison.. ask recent coworkers about their companies as well

Also include NGO? 🤗💞

**Comment by viktorko99** [comment]
use this with #26 ?

**Comment by yangwao** [comment]
yeah done 
- https://cowork.progressbar.sk/our-residents
