### ISSUE TITLE
Update images

### ISSUE THREAD

**Issue by olso** [Progressbar/progressbar-coweb#60]

**Comment by olso** [comment]
https://photos.app.goo.gl/uWnB7AeSX613vUFA3

**Comment by yangwao** [comment]
We have bit professional photos here from Adam https://photos.app.goo.gl/gwgKWBPF78h8GQQV6

I would like to combine them ~

**Comment by yangwao** [comment]
I'll make separate component for meeting room.
And sort out more photos around

**Comment by yangwao** [comment]
https://cowork.progressbar.sk/#/meeting-room-cowork-bratislava

**Comment by olso** [comment]
4071ce1b4fe273746078503ddcf42815b868bb65

**Comment by yangwao** [comment]
Already done
