### ISSUE TITLE
Hackathon 16.12.2018 Agenda

### ISSUE THREAD

**Issue by olso** [Progressbar/progressbar-coweb#61]
Deploy website: https://pbhackathon.netlify.com
Code: https://github.com/Progressbar/progressbar-coweb/tree/hackathon/web

# Design
We wanna follow this? https://github.com/Progressbar/Progressbar-Improvement-Proposal/issues/125

# Issues in this repo and issues from PIP (under)

https://github.com/Progressbar/Progressbar-Improvement-Proposal/issues/15

https://github.com/Progressbar/Progressbar-Improvement-Proposal/issues/16

https://github.com/Progressbar/Progressbar-Improvement-Proposal/issues/20

https://github.com/Progressbar/Progressbar-Improvement-Proposal/issues/60

https://github.com/Progressbar/Progressbar-Improvement-Proposal/issues/105

https://github.com/Progressbar/Progressbar-Improvement-Proposal/issues/59

https://github.com/Progressbar/Progressbar-Improvement-Proposal/issues/58

# Pages with extra care

* https://cowork.progressbar.sk/#/sponsors
* events

**Comment by viktorko99** [comment]
Hackaton will take place at 16.12. Any help is appreciated

**Comment by yangwao** [comment]
🙏🌈🧚‍♂️

**Comment by olso** [comment]
New logos https://github.com/Progressbar/presskit/tree/master/logo_v1.5

**Comment by Ivkaa** [comment]
I created a milestone named Hackathon for this purpose, please mark all related issues :)

**Comment by Ivkaa** [comment]
Schedule:
10.00 - doors open
10.15 - intro to what we want to achieve and how - tech stack, intro to issues
11.30 - lunch
12.30 - hack
15.00 - coffee break (black?)
between 17.30 and 18.00 - closing ceremony and prizes giveaway

**Comment by yangwao** [comment]
https://t.me/joinchat/Bv6P6xDBFDYdEEyhjpInxQ

**Comment by yangwao** [comment]
🌈 This is our public hackathon channel for our new webpage
🌈 Make yourself going https://www.facebook.com/events/300821880533855/ 
🌈 Invite link for this channel https://t.me/joinchat/Bv6P6xDBFDYdEEyhjpInxQ  
🌈 Share on your timeline to attract more people, even non-coding folks are welcome https://www.facebook.com/progressbar/posts/2530820633600530  
🌈 Main issue for this hackathon https://github.com/Progressbar/progressbar-coweb/issues/61

**Comment by anettrolikova** [comment]
IMPROVE - visible mistakes 
- wip waiting for omaksi 
-update pics (we have so much of them - from events / Adam - photographer)
    /on web
   / on google
- drinks update - we don't have matcha either speciality coffe but we have various tea's 
- register for cowork -> delete
- send login -> delete (we dont have newsletters )
- membership  -> presmerovanie na membership nie na linky na social etc.
- podium lane delete 
- update logo
- put google calendar of meeting room so peps can see when it's booked 
  // prolly can think + create how they can book it without need to text to someone/ public channel :) 
- in @viktorko99 update change icons to white (then to pink - Viki understands my point)
- prolly change look to this theme : 
![pozadievap](https://user-images.githubusercontent.com/44020788/49969043-c644b880-ff27-11e8-875e-0cc714dddd08.jpg)
[https://www.dropbox.com/s/aagi8ad5zusn07x/pozadievap.jpeg?dl=0](url)

**Comment by olso** [comment]
Deploy website: https://pbhackathon.netlify.com
Code: https://github.com/Progressbar/progressbar-coweb/tree/hackathon/web
