### ISSUE TITLE
Notable people in space

### ISSUE THREAD

**Issue by yangwao** [Progressbar/progressbar-coweb#64]
As we are not standard cowork.. I would like put our special core members who are running space and have some niche experience in various industries.

Main sponsors.. @yangwao Martin Kustek

Operational patrols @Ivkaa @olso 

Advisors @omaksi ..

Valuable hosts..

Community behind scenes..

And so on

I would come back to it, just draft basic construct

**Comment by olso** [comment]
Also

https://blockunison.com/community

https://www.facebook.com/events/510497772365948/ vitalik event

**Comment by viktorko99** [comment]
@yangwao solved by: https://cowork.progressbar.sk/our-residents ?

**Comment by yangwao** [comment]
yes, done for now.
