### ISSUE TITLE
Dev preview for netlify

### ISSUE THREAD

**Issue by yangwao** [Progressbar/progressbar-coweb#67]
We can have some trash-dev preview branch build on netlify, before production, bc we are trying to be serious here 😅
![image](https://user-images.githubusercontent.com/5887929/47618140-d4ea2400-dacf-11e8-95cb-f7a410a75c7b.png)

**Comment by olso** [comment]
This is now done

https://app.netlify.com/sites/pbweb/overview is deploying 'develop' branch

https://app.netlify.com/sites/progressbar-cowork/overview is deploying 'master' branch

**Comment by olso** [comment]
`develop` is now a default branch

**Comment by yangwao** [comment]
Public address is https://pbweb.netlify.com/#/
