### ISSUE TITLE
Add banner on old website which points to cowork 🔥

### ISSUE THREAD

**Issue by olso** [Progressbar/progressbar-coweb#69]
Add this code above `header-wrapper`

```html
<div id="redirect-wrapper" style="padding: 4rem; text-align: center; border-bottom: 1px solid white;"><p>Please use</p>
    
    <a href="https://cowork.progressbar.sk" style="color: blue; font-size: 3rem; text-decoration: underline;">https://cowork.progressbar.sk</a>
    </div>
```

**Comment by Ivkaa** [comment]
@keram ako to vyzera? :)

**Comment by anettrolikova** [comment]
@keram can you shut down that webpage & leave only text saying this web page is redirect to https://cowork.progressbar.sk/#/ ? :)

**Comment by olso** [comment]
@anettrolikova What about SEO, old links? This deletion could potentially wipe us off 1st/2nd page in Google 🔥 Essentially loosing coworkers

**Comment by keram** [comment]
yeah, @olso is right, we need good migration strategy to ensure that all existing links will still work. 
Btw I will be week before Xmas in Slovakia and planning work from Progressbar some days as well.
.We can organise something to work together on new/old web then.

**Comment by yangwao** [comment]
Because of linkbuilding and SEO positions was my argument not wipe off old web till we figure it out.

Before we teardown old web, we should at least harvest calendar links at with description of events in some reasonable format and archive in some searchable and indexable form.

**Comment by keram** [comment]
My idea is to move the current main web to subdomain something like `old.progressbar.sk`.
Setup 301 redirects on ``www.progressbar.sk/x``  point to  ``old.progressbar.sk/x``
Put new web on www.progressbar.sk

**Comment by Ivkaa** [comment]
continue on #84
