### ISSUE TITLE
Setup web scraping to map to the old domain (progerssbar.sk) so we can change it

### ISSUE THREAD

**Issue by Ivkaa** [Progressbar/progressbar-coweb#84]
Ask for more info @yangwao or @olso

**Comment by Ivkaa** [comment]
#75

**Comment by Ivkaa** [comment]
![image](https://user-images.githubusercontent.com/16141183/49702428-44d3ea00-fbf8-11e8-9072-246ffc512d43.png)

**Comment by yangwao** [comment]
old calendar.json is already there here 
continue here -> https://github.com/Progressbar/progressbar-coweb/issues/75
